# 點事件的空間型態 {#PointEvents}

## 空間型態分析之前的準備動作

點事件發生地點(雨量、震央、犯罪地點等)通常必須要一組x-y的座標對應，稱為**地址對位(address matching)**，畫下座標可以了解事件分布型態。


## 空間分布的中心趨勢

空間分布的中心趨勢有三種不同的指標可以描述：**平均中心點**(mean center)、**中位數中心點**(median center)、**中心地理物件**(central feature)

### 平均中心點

簡單而言，就是平均($\mu$)的概念：

$$
\begin{align}
\bar{x} = \frac{1}{n}\sum_{i=1}^nx_i
\\
\bar{y} = \frac{1}{n}\sum_{i=1}^ny_i
\end{align}
$$
若事件具有權重的概念，例如：醫院的病床數或者是在學人數等，可以再加上加權($w$)的概念：

$$
\begin{align}
\bar{x} = \frac{\sum_{i=1}^n(w_ix_i)}{\sum_{i=1}^nw_i}
\\
\bar{y} = \frac{\sum_{i=1}^n(w_iy_i)}{\sum_{i=1}^nw_i}
\end{align}
$$

要小心的事，一般來說，這個平均值($\bar{x}$,$\bar{y}$)並不是事件的發生地，而且通常無法表示任何群聚點。

### 中位數中心點

當想找出商店的最佳設置點時，可以計算**中位數中心點**，表示該點距離所有地物的距離總和最小，以常理來說最容易到達。一般來說距離為直線距離，因此公式如下：
$$
\begin{align}
Minimize\ \sum_id_i^t = \sum_i\sqrt{(x_i-x^t)^2+(y_i-y^t)^2}
\end{align}
$$

其中$d_i^t$為$i$點到中位數中心點的距離；$x^t、y^t$為中位數中心點，並不是事件發生的點。

當然直線距離也是可以使用其他概念代替，例如：旅行成本(時間加上移動成本)等等。

### 中心地理物件

**中心地理物件**代表在該群體中，距離其他物件總和距離最小的物件。例如：想要在高雄市的某一間學校舉辦邀請各學校來參加的活動，在沒有其他任何條件限制下想要選一個距離所有學校最近的那間學校，該學校即為**中心地理物件**。


## 空間分布的分散程度

### 標準距離
**標準距離**(standard deviation)，又稱**標準距離偏差**(standard distance deviation)這個和標準差有相似的概念，就是看資料與資料平均點的距離有多近，標準差越小就是越集中，越大就是越分散，公式為：
$$
SD = \sqrt{\frac{\sum_i(x_i-\bar{x})^2}{n}+\frac{\sum_i(y_i-\bar{y})^2}{n}}
$$
最後以平均中心點為圓心，以$SD$為半徑畫一個圓，即可畫出一個圓，圓越小表示事件分布越集中。

若加上權重的概念，就可以將以上的公式改寫成：
$$
SD_w = \sqrt{\frac{\sum_iw_i(x_i-\bar{x})^2}{\sum_iw_i}+\frac{\sum_iw_i(y_i-\bar{y})^2}{\sum_iw_i}}
$$

### 標準差橢圓

若事件的群聚具有方向性，例如台灣本島是長長的一根地瓜，主要都是南北分布，因此標準差可以改為**標準差橢圓**(standard deviational ellipse)(上為原始，下為加入權重)：
$$
\begin{gather*}
SD_x = \sqrt{\frac{\sum_i(x_i-\bar{x})^2}{n}}\ ; \ SD_y = \sqrt{\frac{\sum_i(y_i-\bar{y})^2}{n}}\\\\
SD_{wx} = \sqrt{\frac{\sum_iw_i(x_i-\bar{x})^2}{\sum_iw_i}}\ ; \ SD_{wy} = \sqrt{\frac{\sum_iw_i(y_i-\bar{y})^2}{\sum_iw_i}}
\end{gather*}
$$

上面是東西($x$軸)與南北($y$軸)的標準距離，若要計算地物方向，要先計算所有地物與$y$的距離，再將$y$軸旋轉一點角度然後再計算一次與$y$的距離，直到找到距離最小的那個方向為止，紀錄此時$y$軸的旋轉角度，並將$x$也一起旋轉(就是讓兩軸依舊保持直角)，就是該物件分布的角度。

方向性可以看出事件分布的型態，例如犯罪率是否會與主要幹道的方向相同等等。
