# R 實作 02  {#a4_Rmap02}

## 台灣旅館數量

```{r, warning=F, message=F}
library(tidyverse)

sf_taiwan <- sf::read_sf("sf_taiwan\\sf_taiwan.shp")
 sf_taiwan_simplify <- sf_taiwan %>%
  rmapshaper::ms_simplify() # 簡化圖形
sf_hotel <-sf::read_sf("Hotel_E_f\\Hotel_E_f.shp")
```


```{r}
sf_taiwan_simplify %>% sf::st_crop(
    xmin=119, xmax=123,
    ymin=21, ymax=26
  ) %>% 
  ggplot()+  # 第一層是sf_taiwan, 以它的CRS為主
  geom_sf()+
  geom_sf(data=sf_hotel, size = 0.1, color= "#8f2e14", alpha = 0.5) + theme(panel.background = element_rect(fill='#c1e4e9'),                        panel.grid.major=element_line(colour=NA))


```

## 中心點

**以台南市為例**

畫圖：

```{r, warning=F, message=F}
library(aspace)
library(sf)
sf_Tainan <- sf_taiwan %>% subset(COUNTYNAME == "臺南市")
sf_hotel_Tainan <- (sf_hotel %>% subset(Region  == "Tainan City"))

Tainana.hetol.plot <- 
sf_Tainan %>% st_crop(
    xmin=118, xmax=121,
    ymin=22, ymax=24
  ) %>% 
  ggplot()+  # 第一層是sf_taiwan, 以它的CRS為主
  geom_sf()+
  geom_sf(data=sf_hotel_Tainan, size = 1, color= "#7b8d42", alpha= 0.5) + 
  theme(panel.background = element_rect(fill='#c1e4e9'),                        panel.grid.major=element_line(colour=NA))
Tainana.hetol.plot
```

整理資料：
```{r tidy data, include=F, message=F}
sf_hotel_Tainan.xy <- (sf_hotel_Tainan %>% as.data.frame)[,c(15,16)]
sf_hotel_Tainan.xy$Px <- sf_hotel_Tainan.xy$Px %>% as.numeric()
sf_hotel_Tainan.xy$Py <- sf_hotel_Tainan.xy$Py %>% as.numeric()
```


### mean center
```{r warning=F, message=F}
mean_c <- mean_centre(id=1, filename="sf_hotel_Tainan", 
weighted=FALSE, weights=NULL, points=sf_hotel_Tainan.xy)

```

### median center
```{r warning=F, message=F}
median_c <- median_centre(id=1, filename="sf_hotel_Tainan", 
points=sf_hotel_Tainan.xy)
```

### mean center
```{r warning=F, message=F}
CF <- CF(id=1, filename="sf_hotel_Tainan", points=sf_hotel_Tainan.xy)
```

另外還有一個是課本裡沒提到的：
- **Centre of Minimum Distance**


```{r warning=F, message=F}
# CMD(id=1, filename="sf_hotel_Tainan", dist=10, 
# points=sf_hotel_Tainan.xy)
```


### 比較三個中心點：

```{r warning=F, message=F}
Tainana.hetol.plot +geom_point(mapping = aes(x = CF$CF.x, y = CF$CF.y), shape = 11, color = "#483c4d", size = 3, alpha = 0.8)+
  geom_point(mapping = aes(x = mean_c$CENTRE.x, y = mean_c$CENTRE.y))+
   geom_point(mapping = aes(x = median_c$median.x, y = median_c$median.y), shape = 1, color = "#420a00", size = 3, alpha = 0.7)+
  labs(x = "", y = "")
```

## 橢圓


```{r  warning=F, message=F}
 calc_sde(id=1,points=sf_hotel_Tainan.xy)

```
## plot the ellipse
```{r}
rotation = function(a){
  r = a * pi / 180 #degrees to radians
  matrix(c(cos(r), sin(r), -sin(r), cos(r)), nrow = 2, ncol = 2) %>% return()
}   # 旋轉矩陣(Rotation matrix)

CENTRE.x <- mean(sf_hotel_Tainan.xy$Px); CENTRE.y <- mean(sf_hotel_Tainan.xy$Py) # 圓心，就是平均
Sigma.x = 0.07563829; Sigma.y = 0.2038352 # 半徑

theta <- 38.73579* pi / 180
t <- rotation(theta)

library(ggforce)

Tainana.hetol.plot+
  geom_point(mapping = aes(x = CENTRE.x, y = CENTRE.y))+
  geom_abline(intercept = CENTRE.y-CENTRE.x*tan(theta), slope = tan(theta))+
  geom_abline(intercept = CENTRE.y+CENTRE.x*(tan(theta)), slope = -tan(theta))+
  geom_ellipse(aes(x0 = CENTRE.x, y0 = CENTRE.y, a = Sigma.y, b = Sigma.x, angle = theta)) 
  



```

但是要小心的是，這和進行回歸的點圖很像，要小心離群值（就是離大家很遠的值）會影響方向性的呈現。

## 畫地圖

這裡我們用`tmap`，來畫一下台南的人口分布：

```{r set up, warning=FALSE, message=F}
rm(list=ls())
library(tidyverse)
library(spData)
library(sf)
```


```{r read the data, warning=FALSE, message=F}
sf_taiwan_town <- sf::read_sf("C:/Users/ChenWenRu/OneDrive - 國立成功大學 National Cheng Kung University/R_Project/Spatial Analysis/mapdata202104280245\\TOWN_MOI_1100415.shp")
sf_tainan_pop <- read.csv("Tainan_pop.csv", fileEncoding = "Big5")
colnames(sf_tainan_pop) <- c("TOWNNAME", "population","male_pop","female_pop" )

sf_Tainan_town <- sf_taiwan_town %>% filter(COUNTYNAME == "臺南市")
sf_Tainan_town <- left_join(sf_Tainan_town,sf_tainan_pop[,c(1,2)])

# 讀旅館資料
sf_hotel <-sf::read_sf("C:/Users/ChenWenRu/OneDrive - 國立成功大學 National Cheng Kung University/R_Project/Spatial Analysis/Hotel_E_f\\Hotel_E_f.shp")
sf_hotel_Tainan <- (sf_hotel %>% subset(Region  == "Tainan City"))

```

```{r}
library(tmap)

tm_shape(sf_Tainan_town) + tm_polygons(col="population", n = 10, border.col = "white", palette = "Greens")+ # n: 幾個級距 ; 可在裡面加上 breaks = c(0, 23000, 27000, 100000 ) 照裡面的數字分級
  tm_legend(outside = TRUE) #legend 是否在外面
```
```{r warning=F, message=F}
# 讀旅館資料
sf_hotel <-sf::read_sf("Hotel_E_f\\Hotel_E_f.shp")
sf_hotel_Tainan <- (sf_hotel %>% subset(Region  == "Tainan City"))

tm_shape(sf_Tainan_town) + tm_polygons(col="population", n = 10, border.col = "white", palette = "Greens",legend.hist = TRUE)+ # n: 幾個級距 ; 可在裡面加上 breaks = c(0, 23000, 27000, 100000 ) 照裡面的數字分級; legend.hist 長條圖
  tm_legend(outside = TRUE)+ #legend 是否在外面
  tm_shape(sf_hotel_Tainan) + # 加上旅館個數的點點   
    tm_dots(size=  .1, col ="black") 
```
人口與旅館數量的地圖

```{r , warning=FALSE, message=F}
sf_taiwan_town <- sf::read_sf("Taiwan_Town\\TOWN_MOI_1100415.shp")
sf_tainan_pop <- read.csv("Tainan_pop.csv", fileEncoding = "Big5")
colnames(sf_tainan_pop) <- c("TOWNNAME", "population","male_pop","female_pop" )

sf_Tainan_town <- sf_taiwan_town %>% filter(COUNTYNAME == "臺南市")
sf_Tainan_town <- left_join(sf_Tainan_town,sf_tainan_pop[,c(1,2)])

# 讀旅館資料
sf_hotel <-sf::read_sf("Hotel_E_f\\Hotel_E_f.shp")
sf_hotel_Tainan <- (sf_hotel %>% subset(Region  == "Tainan City"))

```

```{r 北部疫情, warning=FALSE, message=F}
sf_taiwan_town <- sf::read_sf("Taiwan_Town\\TOWN_MOI_1100415.shp")
sf_tainan_pop <- read.csv("Tainan_pop.csv", fileEncoding = "Big5")
colnames(sf_tainan_pop) <- c("TOWNNAME", "population","male_pop","female_pop" )

sf_Tainan_town <- sf_taiwan_town %>% filter(COUNTYNAME == "臺南市")
sf_Tainan_town <- left_join(sf_Tainan_town,sf_tainan_pop[,c(1,2)])

# 讀旅館資料
sf_hotel <-sf::read_sf("Hotel_E_f\\Hotel_E_f.shp")
sf_hotel_Tainan <- (sf_hotel %>% subset(Region  == "Tainan City"))

```

資料來源：

https://data.gov.tw/dataset/73280

https://rstudio-pubs-static.s3.amazonaws.com/202534_2c5edc19016247ac9ecfc5713b4604f2.html

人口資料：
https://bca.tainan.gov.tw/News_Content.aspx?n=1134&s=8157

http://spatstat.org/ECAS2019/notes/notes03.html

Point pattern analysis in R
https://mgimond.github.io/Spatial/point-pattern-analysis-in-r.html


資料來源：

https://data.gov.tw/dataset/73280

https://rstudio-pubs-static.s3.amazonaws.com/202534_2c5edc19016247ac9ecfc5713b4604f2.html
